name: Sixvox Automation
on:
  workflow_dispatch:
    inputs:
      login:
        description: 'Login do Sixvox'
        required: true
        type: string
      senha:
        description: 'Senha do Sixvox'
        required: true
        type: string

jobs:
  run-sixvox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager
          
      - name: Executar script
        env:
          LOGIN: ${{ github.event.inputs.login }}
          SENHA: ${{ github.event.inputs.senha }}
        run: python codigo_python.py
