name: Sixvox Automation

on:
  workflow_dispatch:
    inputs:
      nome:
        description: 'Nome do cliente'
        required: true
        type: string
      telefone:
        description: 'Telefone do cliente'
        required: true
        type: string
      email:
        description: 'Email do cliente'
        required: true
        type: string

jobs:
  executar-automacao:
    runs-on: ubuntu-latest
    permissions: write-all
    
    env:
      LOGIN: ${{ secrets.LOGIN }}
      SENHA: ${{ secrets.SENHA }}
      NOME: ${{ github.event.inputs.nome }}
      TELEFONE: ${{ github.event.inputs.telefone }}
      EMAIL: ${{ github.event.inputs.email }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2
        with:
          chrome-version: 131
          install-chromedriver: 131.0.6778.264
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Executar script de automação
        run: python codigo_python.py
