name: Sixvox Automation

on:
  repository_dispatch:
    types: [automation_trigger]

jobs:
  executar-automacao:
    runs-on: ubuntu-latest
    permissions: write-all
    
    env:
      LOGIN: ${{ secrets.LOGIN }}
      SENHA: ${{ secrets.SENHA }}
      # Dados Pessoais
      NOME_CORRETOR: ${{ github.event.client_payload.dados_pessoais.nome_corretor }}
      NOME_SOCIO: ${{ github.event.client_payload.dados_pessoais.nome_socio }}
      GRADE: ${{ github.event.client_payload.dados_pessoais.grade }}
      TELEFONE: ${{ github.event.client_payload.dados_pessoais.telefone }}
      EMAIL: ${{ github.event.client_payload.dados_pessoais.email }}
      # Dados Profissionais
      UNIDADE: ${{ github.event.client_payload.dados_profissionais.unidade }}
      EQUIPE: ${{ github.event.client_payload.dados_profissionais.equipe }}
      DATA_ENTRADA: ${{ github.event.client_payload.dados_profissionais.data_entrada }}
      # Endereço
      ENDERECO: ${{ github.event.client_payload.endereco.logradouro }}
      BAIRRO: ${{ github.event.client_payload.endereco.bairro }}
      CIDADE: ${{ github.event.client_payload.endereco.cidade }}
      CEP: ${{ github.event.client_payload.endereco.cep }}
      ESTADO: ${{ github.event.client_payload.endereco.estado }}
      # Documentos
      DATA_NASCIMENTO: ${{ github.event.client_payload.documentos.data_nascimento }}
      CPF: ${{ github.event.client_payload.documentos.cpf }}
      CNPJ: ${{ github.event.client_payload.documentos.cnpj }}
      RG: ${{ github.event.client_payload.documentos.rg }}
      # Dados Bancários
      BANCO: ${{ github.event.client_payload.dados_bancarios.banco }}
      CODIGO_BANCO: ${{ github.event.client_payload.dados_bancarios.codigo_banco }}
      AGENCIA: ${{ github.event.client_payload.dados_bancarios.agencia }}
      CONTA: ${{ github.event.client_payload.dados_bancarios.conta }}
      TIPO_CONTA: ${{ github.event.client_payload.dados_bancarios.tipo_conta }}
      # Dados do Titular
      TITULAR_CONTA: ${{ github.event.client_payload.dados_titular.titular_conta }}
      TITULAR_CPF: ${{ github.event.client_payload.dados_titular.titular_cpf }}
      # Dados PIX
      CHAVE_PIX: ${{ github.event.client_payload.dados_pix.chave_pix }}
      TIPO_PIX: ${{ github.event.client_payload.dados_pix.tipo_pix }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2
        with:
          chrome-version: 131
          install-chromedriver: 131.0.6778.264
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Executar script de automação
        run: python codigo_python.py
