name: Sixvox Automation

on:
  repository_dispatch:
    types: [automation_trigger]

jobs:
  executar-automacao:
    runs-on: ubuntu-latest
    permissions: write-all
    
    env:
      LOGIN: ${{ secrets.LOGIN }}
      SENHA: ${{ secrets.SENHA }}
      NOME: ${{ github.event.client_payload.nome }}
      TELEFONE: ${{ github.event.client_payload.telefone }}
      EMAIL: ${{ github.event.client_payload.email }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2
        with:
          chrome-version: 131
          install-chromedriver: 131.0.6778.264
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Executar script de automação
        run: python codigo_python.py
