name: Python Automation
on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Dados recebidos do n8n'
        required: true
        type: string

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Executar script
        run: |
          echo "Dados recebidos: ${{ github.event.inputs.data }}"
          python seu_script.py "${{ github.event.inputs.data }}"
